rename release workflows

diff --git a/.github/workflows/release-1-create-pr.yml b/.github/workflows/release-1-create-pr.yml
--- a/.github/workflows/release-1-create-pr.yml
+++ b/.github/workflows/release-1-create-pr.yml
@@ -47,9 +47,19 @@ jobs:
           sed -ri "s/__version__ = '.*'/__version__ = '${{ github.event.inputs.release_number }}'/" dojo/__init__.py
           sed -ri "s/appVersion: \".*\"/appVersion: \"${{ github.event.inputs.release_number }}\"/" helm/defectdojo/Chart.yaml
           sed -ri "s/\"version\": \".*\"/\"version\": \"${{ github.event.inputs.release_number }}\"/" components/package.json
-          # remove the -dev suffix to make it the new final version in master
-          CURRENT_CHART_VERSION=$(grep -oP 'version: (\K\S*)?' helm/defectdojo/Chart.yaml)
-          sed -ri "s/version: \S+/version: ${CURRENT_CHART_VERSION%-*}/" helm/defectdojo/Chart.yaml
+
+          grep -q "\-dev" helm/defectdojo/Chart.yaml
+          if [ $? -eq 0 ]
+          then
+              echo "-dev found in Chart.yaml, probably releasing a new minor version"
+              echo "removing the -dev suffix"
+              sed -e "s/\-dev//" -i helm/defectdojo/Chart.yaml
+          else
+              echo "-dev NOT found in Chart.yaml, probably releasing a new bug fix version"
+              echo "bumping the chart version"
+              CURRENT_CHART_VERSION=$(grep -oP 'version: (\K\S*)?' helm/defectdojo/Chart.yaml)
+              sed -ri "s/version: \S+/$(echo "version: $CURRENT_CHART_VERSION" | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}')/" helm/defectdojo/Chart.yaml
+          fi
 
       - name: Check numbers
         run: |
