Update unit-tests.yml

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -44,6 +44,16 @@ jobs:
             exit 1
           fi
 
+      - name: Check Django version
+        run: |
+          echo "Checking Django version..."
+          INSTALLED_VERSION=$(pip show django | grep Version | cut -d ' ' -f 2)
+          REQUIRED_VERSION="4.2.4"  # Укажите желаемую версию Django
+          if [ "$INSTALLED_VERSION" != "$REQUIRED_VERSION" ]; then
+            echo "Incorrect Django version installed: $INSTALLED_VERSION. Required: $REQUIRED_VERSION"
+            exit 1
+          fi
+
       - name: Run unit tests
         run: |
           pytest --junitxml=test-results.xml || true
