Update unit-tests.yml
Исправленная конфигурация unit-tests.yml с Flask

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -39,18 +39,18 @@ jobs:
         run: |
           echo "Validating installed packages..."
           pip list
-          if ! pip show django; then
-            echo "Django is not installed or version mismatch!"
+          if ! pip show flask; then
+            echo "Flask is not installed!"
             exit 1
           fi
 
-      - name: Check Django version
+      - name: Check Flask version
         run: |
-          echo "Checking Django version..."
-          INSTALLED_VERSION=$(pip show django | grep Version | cut -d ' ' -f 2)
-          REQUIRED_VERSION="4.2.4"  # Укажите желаемую версию Django
+          echo "Checking Flask version..."
+          INSTALLED_VERSION=$(pip show flask | grep Version | cut -d ' ' -f 2)
+          REQUIRED_VERSION="2.3.2"  # Укажите желаемую версию Flask
           if [ "$INSTALLED_VERSION" != "$REQUIRED_VERSION" ]; then
-            echo "Incorrect Django version installed: $INSTALLED_VERSION. Required: $REQUIRED_VERSION"
+            echo "Incorrect Flask version installed: $INSTALLED_VERSION. Required: $REQUIRED_VERSION"
             exit 1
           fi
 
